// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz43BVul1avoOnycUyYjEe022-w9Q52kE',
    appId: '1:665954830552:web:786ce790c0e8ce0dcfefad',
    messagingSenderId: '665954830552',
    projectId: 'trabalho-3-mobile',
    authDomain: 'trabalho-3-mobile.firebaseapp.com',
    storageBucket: 'trabalho-3-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIgsFYSXuCS9P3_j4TjNQD0PIiYJh-LKE',
    appId: '1:665954830552:android:6719daf6f960674fcfefad',
    messagingSenderId: '665954830552',
    projectId: 'trabalho-3-mobile',
    storageBucket: 'trabalho-3-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7OJr1_Z8swXu-PA81Epbl9MGZLAXarfU',
    appId: '1:665954830552:ios:115db7c31a9d322acfefad',
    messagingSenderId: '665954830552',
    projectId: 'trabalho-3-mobile',
    storageBucket: 'trabalho-3-mobile.firebasestorage.app',
    iosBundleId: 'com.example.trabalho3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7OJr1_Z8swXu-PA81Epbl9MGZLAXarfU',
    appId: '1:665954830552:ios:115db7c31a9d322acfefad',
    messagingSenderId: '665954830552',
    projectId: 'trabalho-3-mobile',
    storageBucket: 'trabalho-3-mobile.firebasestorage.app',
    iosBundleId: 'com.example.trabalho3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz43BVul1avoOnycUyYjEe022-w9Q52kE',
    appId: '1:665954830552:web:33e0d4da595e9b26cfefad',
    messagingSenderId: '665954830552',
    projectId: 'trabalho-3-mobile',
    authDomain: 'trabalho-3-mobile.firebaseapp.com',
    storageBucket: 'trabalho-3-mobile.firebasestorage.app',
  );
}
